package com.example.ui.theme

enum class AppLanguage(val code: String, val label: String) {
    ENGLISH("en", "English"),
    TAMIL("ta", "தமிழ்")
}

class Localization(val language: AppLanguage) {
    val map = when (language) {
        AppLanguage.ENGLISH -> mapOf(
            "appName" to "Rio Share",
            "tagline" to "Fast & Secure P2P Sharing",
            "send" to "Send",
            "receive" to "Receive",
            "history" to "History",
            "photos" to "Photos",
            "videos" to "Videos",
            "documents" to "Documents",
            "apks" to "APKs",
            "others" to "Others",
            "selectFiles" to "Select Files",
            "selectedFiles" to "Selected %d files (%s)",
            "next" to "Next",
            "searchingDevices" to "Searching for nearby devices...",
            "connecting" to "Connecting to %s...",
            "connectedTo" to "Connected to %s",
            "waitingSender" to "Waiting for sender...",
            "scanQrTitle" to "Scan QR to Connect",
            "scanQrSub" to "Align the receiver's QR code in the frame",
            "showMyQr" to "My QR Code",
            "speed" to "Speed",
            "remainingTime" to "Remaining",
            "completed" to "Completed",
            "failed" to "Failed",
            "transferHistory" to "Transfer History",
            "noHistory" to "No history yet. Start sharing!",
            "clearHistory" to "Clear History",
            "sendSuccess" to "Sent successfully!",
            "receiveSuccess" to "Received successfully!",
            "secureActive" to "Secure AES-256 Connection Active",
            "oneTap" to "One-Tap Share",
            "language" to "Language / மொழி",
            "darkMode" to "Dark Theme",
            "recent" to "Recent Transfers",
            "totalShared" to "Total Shared",
            "totalReceived" to "Total Received",
            "noDevices" to "No devices found yet. Tap to refresh.",
            "availableDevices" to "Available Devices",
            "tapToConnect" to "Tap to connect & start transfer",
            "simScanQr" to "Simulate QR Scanner Scan",
            "backToHome" to "Back to Home",
            "transferProgress" to "Transfer Progress",
            "averageSpeed" to "Average Speed",
            "fileSize" to "Total Size",
            "activeFile" to "Active File: %s",
            "done" to "Done",
            "cancel" to "Cancel",
            "sending" to "Sending...",
            "receiving" to "Receiving...",
            "deviceDiscovery" to "Device Discovery",
            "quickStats" to "Transfer Overview",
            "mockScannerHint" to "Simulating camera QR scanner... Wave phone near receiving device QR code.",
            "securePrompt" to "Transfer is secured with an end-to-end unique pairing PIN.",
            "tamilSelected" to "தமிழ் தேர்ந்தெடுக்கப்பட்டது",
            "englishSelected" to "English Selected"
        )
        AppLanguage.TAMIL -> mapOf(
            "appName" to "ரியோ ஷேர்",
            "tagline" to "வேகமான மற்றும்安全的 P2P பகிர்வு",
            "send" to "அனுப்புக",
            "receive" to "பெறுக",
            "history" to "வரலாறு",
            "photos" to "புகைப்படங்கள்",
            "videos" to "வீடியோக்கள்",
            "documents" to "ஆவணங்கள்",
            "apks" to "செயலிகள் (APK)",
            "others" to "இதர",
            "selectFiles" to "கோப்புகளைத் தேர்ந்தெடு",
            "selectedFiles" to "%d கோப்புகள் தேர்ந்தெடுக்கப்பட்டுள்ளன (%s)",
            "next" to "அடுத்து",
            "searchingDevices" to "அருகிலுள்ள சாதனங்களைத் தேடுகிறது...",
            "connecting" to "%s உடன் இணைக்கிறது...",
            "connectedTo" to "%s உடன் இணைக்கப்பட்டுள்ளது",
            "waitingSender" to "அனுப்புநருக்காகக் காத்திருக்கிறது...",
            "scanQrTitle" to "இணைக்க QR-ஐ ஸ்கேன் செய்க",
            "scanQrSub" to "பெறுநரின் QR குறியீட்டை உள்ளே சீரமைக்கவும்",
            "showMyQr" to "என் QR குறியீடு",
            "speed" to "வேகம்",
            "remainingTime" to "மீதமுள்ள நேரம்",
            "completed" to "முடிக்கப்பட்டது",
            "failed" to "தோல்வியடைந்தது",
            "transferHistory" to "பகிர்வு வரலாறு",
            "noHistory" to "பகிர்வு வரலாறு எதுவும் இல்லை. தொடங்குக!",
            "clearHistory" to "வரலாற்றை அழி",
            "sendSuccess" to "வெற்றிகரமாக அனுப்பப்பட்டது!",
            "receiveSuccess" to "வெற்றிகரமாகப் பெறப்பட்டது!",
            "secureActive" to "பாதுகாப்பான AES-256 இணைப்பு செயலில் உள்ளது",
            "oneTap" to "ஒரே தட்டலில் பகிர்வு",
            "language" to "மொழி / Language",
            "darkMode" to "இருண்ட பயன்முறை",
            "recent" to "சமீபத்திய பரிமாற்றங்கள்",
            "totalShared" to "பகிரப்பட்டவை",
            "totalReceived" to "பெறப்பட்டவை",
            "noDevices" to "சாதனங்கள் எதுவும் இன்னும் கண்டறியப்படவில்லை.",
            "availableDevices" to "கிடைக்கக்கூடிய சாதனங்கள்",
            "tapToConnect" to "இணைக்க தட்டி பகிரத் தொடங்குங்கள்",
            "simScanQr" to "QR ஸ்கேனரை உருவகப்படுத்து",
            "backToHome" to "முகப்புக்குச் செல்க",
            "transferProgress" to "பகிர்வு முன்னேற்றம்",
            "averageSpeed" to "சராசரி வேகம்",
            "fileSize" to "மொத்த அளவு",
            "activeFile" to "செயலில் உள்ள கோப்பு: %s",
            "done" to "முடிந்தது",
            "cancel" to "ரத்து செய்",
            "sending" to "அனுப்புகிறது...",
            "receiving" to "பெறுகிறது...",
            "deviceDiscovery" to "சாதனக் கண்டுபிடிப்பு",
            "quickStats" to "பரிமாற்ற மேலோட்டம்",
            "mockScannerHint" to "கேமரா QR ஸ்கேனர் உருவகப்படுத்தப்படுகிறது... பெறுநரின் QR அருகே கொண்டு செல்லவும்.",
            "securePrompt" to "முப்பரிமாண தனித்துவமான இணைத்தல் பின்னுடன் பகிர்வு பாதுகாக்கப்பட்டுள்ளது.",
            "tamilSelected" to "தமிழ் தேர்ந்தெடுக்கப்பட்டது",
            "englishSelected" to "ஆங்கிலம் தேர்ந்தெடுக்கப்பட்டது"
        )
    }

    fun get(key: String, vararg args: Any): String {
        val format = map[key] ?: key
        return try {
            if (args.isEmpty()) format else java.lang.String.format(format, *args)
        } catch (e: Exception) {
            format
        }
    }
}
